### ISSUE TITLE
Add Secure cookie flag option to session cookie

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Session#106]
The session cookie needs the ability to have the 'Secure' flag set.

This depends on https://github.com/aspnet/HttpAbstractions/issues/612.

Note we considered doing this in the past (https://github.com/aspnet/Session/pull/28), but we considered the Microsoft.AspNetCore.CookiePolicy middleware to be adequate. That's no longer the case because we want to apply token binding data protection based on if the cookie will be marked as Secure.

**Comment by joerter** [comment]
Is this going to be included in the 1.1.0 release?

**Comment by joerter** [comment]
Will this be included in the 1.1.0 release?

**Comment by Tratcher** [comment]
Yes

**Comment by sewarts** [comment]
Using 1.1. but there is no options.Cookie.SecurePolicy = CookieSecurePolicy.Always option

**Comment by Tratcher** [comment]
In 1.1 it's options.CookieSecure 
https://github.com/aspnet/Session/blob/f8b38c9d9c25288fcafcfa54f3d3374d74003ce1/src/Microsoft.AspNetCore.Session/SessionOptions.cs#L42
