### ISSUE TITLE
How to check is session is available/configured

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Session#108]
With NLog users can log session values (e.g. to file). 

In ASP.NET4 this works well, but with this library we have the following issues:

- This could lead to a stackoverflow, as [`DistributedSession.Load` and `DistributedSession.LoadAsync` also writes log messages](https://github.com/aspnet/Session/blob/a82ce5ea77ff6572a2da5c84ab075f03ab4b917e/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L165) - we have made a work around this.
- Reading session could lead to exceptions: `System.InvalidOperationException: Session has not been configured for this application or request.` 

How do we check (without writing a log message) if the session is available/configured, so that we can prevent these issues?

Related https://github.com/aspnet/Session/issues/99, https://github.com/NLog/NLog.Extensions.Logging/issues/28

**Comment by Tratcher** [comment]
To see if it's enabled you can check if `context.Features.Get<ISessionFeature>()?.Session != null`.

**Comment by 304NotModified** [comment]
Thanks!
