### ISSUE TITLE
Bind the cookie to ITlsTokenBindingFeature

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Session#110]
If the cookie is marked as Secure (https://github.com/aspnet/Session/issues/106), bind it to the TLS token (https://github.com/aspnet/Security/issues/773, https://github.com/aspnet/IISIntegration/issues/31)

**Comment by Tratcher** [comment]
@muratg this should be backlogged, the underlying infrastructure from IIS, WebListener, and Kestrel.Https isn't ready.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2406
