### ISSUE TITLE
Session middleware for session affinity

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Session#112]
As far as I remember correctly, in System.Web world, session locks the requests and only allows one request to go through at a time per session (I could be wrong). Is this also the behavior we get with this session middleware?

I want to provide session affinity for my web applications but I am not sure if the session middleware if the right choice to provide that. If it has the lock behavior I mentioned about, it wouldn't fit well.

**Comment by Tratcher** [comment]
No, it does not lock. Right now it's last-write-wins.

**Comment by brockallen** [comment]
Ruh Roh... i'm sure people won't be making parallel requests, so it'll be fine :)
