### ISSUE TITLE
Session is not working on IIS with CORS

### ISSUE THREAD

**Issue by devilsuraj** [aspnet/Session#118]
I am using sessions to manage application state in ASP.NET CORE and it's configured as below.

```
 services.AddSession(options =>
            {
                options.CookieName = ".my.Session";
                options.IdleTimeout = TimeSpan.FromSeconds(20);
            });
```
It's working on localhost but on remote IIS 8 it's not creating cookies so not able to get the values. I also have enabled CORS and don't know what exactly caused this problem. In log it's not showing error either. It's creating session getting stored id but no cookie at client side.

**Comment by kichalla** [comment]
Could you share a sample repro project?

**Comment by devilsuraj** [comment]
thanks for reply i am following this https://github.com/aspnet/MusicStore 
this is the code where session is created  
```
private static string GetCartId(HttpContext context)
        {
            var cartId = context.Session.GetString("Session");

            if (cartId == null)
            {
                //A GUID to hold the cartId. 
                cartId = Guid.NewGuid().ToString();

                // Send cart Id as a cookie to the client.
                context.Session.SetString("Session", cartId);
            }

            return cartId;
        }
```
but tis not working on CORS i am getting cookie in response header but its not set in browser

**Comment by Tratcher** [comment]
What is your CORS policy? Some CORS policies do not allow cookies.

**Comment by devilsuraj** [comment]
@Tratcher as for now i have allowed everything in CORS , anyways after researching a lot i found cookies wont work on cross domain for security reasons. anyways i will get the app on subdomain , will test and close the issue

**Comment by devilsuraj** [comment]
well its not working on subdomains either this is the response header
Set-Cookie:.mysession.Session=e506554c-34b1-8990-de71-a9d12cd4a3ff; domain=.mydomain.com; path=/; httponly

**Comment by Tratcher** [comment]
(not directly related, but it looks like you're still using RC2, you should move to 1.0).

**Comment by muratg** [comment]
This issue was moved to aspnet/CORS#81

**Comment by devilsuraj** [comment]
not working even after updating...

**Comment by davidfowl** [comment]
@devilsuraj Can you be more specific?

**Comment by devilsuraj** [comment]
@davidfowl i have an frontend app (angular2) hosted on app.mydomain.com i am making xhr calls to back.mydomain.com where .net backend app is hosted so when i need to maintain session between users and backend i am using code mentioned in my previous comments . it works if app and backend are both on same server but with CORS i.e. in my case on different domain it fails to create session cookie . its there in response header but not being created so i am not able to maintain session so my app is not working . hope it explains....
