### ISSUE TITLE
Session and SqlServerCache does not share session keys across multiple servers

### ISSUE THREAD

**Issue by mw007** [aspnet/Session#119]
I'm using the following project https://github.com/mw007/SessionSample to reproduce this on ASP.NET Core 1.0

As mentioned in the title, I'm using SqlServerCache to manage session state. What I've noticed	is that when running in a multi-server environment, a different session key is generated for requests coming through different servers. I'd like this key to be shared so that session state is shared between servers.

I've looked at the following docs:

* https://docs.asp.net/en/latest/fundamentals/app-state.html
* https://docs.asp.net/en/latest/performance/caching/distributed.html

In the second doc, I see the following under the *What is a Distributed Cache* section.

> A distributed cache is shared by multiple app servers (see Caching Basics). The information in the cache is not stored in the memory of individual web servers, and the cached data is available to all of the app’s servers. This provides several advantages:
> 
> 1. Cached data is coherent on all web servers. Users don’t see different results depending on which web server handles their request

The way I've set this up is by using NGINX to proxy between both servers. Here is the proxy configuration from my nginx.conf file:

```
upstream backend {
	server localhost:5000;
	server 192.168.121.195:5000 backup;
}

server {
	listen       80;
	server_name  localhost;

	location / {
		proxy_pass http://backend;
		proxy_redirect off;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded_for $remote_addr;
}
```

If I remove the "backup" option from the second server listed in the upstream configuration, a new session key is created for each request. This makes it so the session is basically not used.

Are there options I need to enable before sharing session between app servers will work?

**Comment by Tratcher** [comment]
The session cookie is also protected so you need to share your DataProtection configuration across the machines: https://docs.asp.net/en/latest/security/data-protection/configuration/overview.html

**Comment by mw007** [comment]
Thank you so much! This fixed the issue I was having.
