### ISSUE TITLE
Capture Session timeout on Server side asp.net core

### ISSUE THREAD

**Issue by shafqatdotnet** [aspnet/Session#121]
In Asp.net WebForms there is an event called Seesion_End() in global.asax, whenever session is timeout or you call Session.Abandon() this event handler is executed, i need to have similar kind of behavior in asp.net Core, is it possible?

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Session/issues/20

**Comment by muratg** [comment]
Duplicate
