### ISSUE TITLE
Sharing Cookie name between ASP.NET and ASP.NET core apps

### ISSUE THREAD

**Issue by epignosisx** [aspnet/Session#122]
I was trying to use the ASP.NET_SessionId cookie name to avoid having multiple cookie names (we have a site composed of multiple web apps). However, ASP.NET Core does not take well the cookie value from ASP.NET. I believe the failure is on the CookieProtector.

I think I can get around the problem by writing my own implementation of the SessionMiddleware class and pretty much keep the existing code as it is. However, I think this is a common enough scenario that it would be nice to be provide an extensibility point to allow other cookie value formats.

Is this a sane request or is there a security risk I'm missing?

**Comment by muratg** [comment]
What's the scenario you were thinking?

**Comment by epignosisx** [comment]
We have an IIS Site and a few web apps under it that compose our .com website:
domain.com (ASP.NET)
domain.com/foo (ASP.NET)
domain.com/bar (ASP.NET Core under dev)

It would be nice for all these apps to share the ASP.NET_SessionId cookie as the session identifier instead of each framework having their own cookie.

**Comment by Tratcher** [comment]
Are you trying to share any session data between the apps, or just the cookie key&value?

**Comment by epignosisx** [comment]
Just the cookie name/value to keep things optimized.

**Comment by Tratcher** [comment]
Yeah, there's no way to do that right now.

**Comment by irfanbuyukyangoz** [comment]
@shanselman s@ @muratg #88 #230 
Duplicate of #
