### ISSUE TITLE
1.0.0-rc1-final does not support .NetCoreApp 1.0

### ISSUE THREAD

**Issue by ryios** [aspnet/Session#123]
Is this normal, or a bug.  Or does the code currently not support the latest RC2 1.0.0 of .NetCoreApp?

**Comment by Tratcher** [comment]
Why are you using rc1-final? 1.0 has shipped.

**Comment by ryios** [comment]
I found it yesterday, what confused me is the name of the package changed.

This one is

Microsoft.AspNet.Session

And the one for 1.0.0 is

Microsoft.AspNetCore.Session

**Comment by hishamco** [comment]
All the AspNet packages has been changed to AspNetCore before 1.0.0 is released. For more information please visit this [link](https://github.com/aspnet/Announcements/issues/144)

**Comment by ryios** [comment]
Thank you for the link, exactly what I was looking for.

**Comment by hishamco** [comment]
You 're welcome :smile:

**Comment by JunTaoLuo** [comment]
Looks like there's nothing pending in this issue so closing for now. Please re-open if there are still unresolved issues.
