### ISSUE TITLE
Using ISession with dependency injection

### ISSUE THREAD

**Issue by NVentimiglia** [aspnet/Session#124]
Simply put, I can access ISession using Controller.HttpContext but not using Dependency Injection.

In my app, I have a service  with a dependency on ISession.  ISession can never be resolved, resulting in this error.

`````
 public CartContext(ISession session)
        {
            this.session = session;
        }
`````
> InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.ISession' while attempting to activate 'WebApplication1.Service.CartContext'.

I believe I have this wired correctly, as I can  access the session from the HttpContext within a controller. I guess I can make my service dependent on the controller, but that is exceedingly smelly. My Startup.cs snippets are below.

`````
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDistributedMemoryCache();
            services.AddMemoryCache();

            services.AddSession(options => {
                options.IdleTimeout = TimeSpan.MaxValue;
                options.CookieName = this.GetType().Namespace;
            });

            // Add application services.
           services.AddTransient<CartContext>();
        }

        public async void Configure(
            IApplicationBuilder app,
            IHostingEnvironment env,
            ILoggerFactory loggerFactory)
        {
            
            app.UseSession();
        }
    }
`````

**Comment by davidfowl** [comment]
`ISession` is not a service.

**Comment by NVentimiglia** [comment]
@davidfowl Is there a work around to expose session to dependency injection ?

**Comment by Tratcher** [comment]
Inject IHttpContextAccessor?

**Comment by Tratcher** [comment]
Duplicate: https://github.com/aspnet/Session/issues/88
