### ISSUE TITLE
Handling two or more asynchronous requests using the same session values

### ISSUE THREAD

**Issue by jltjohanlindqvist** [aspnet/Session#126]
How do sessions update their values? 

The problem I'm having is that when I receive two requests belonging to the same session simultaneously and somewhere while processing these requests I update the session in one request for whatever reason, will the other request be able to access that updated value in the session right away? 

Because from the experimenting I've done that doesn't seem to be the case. When I try to read the session in the second request the value in the session has not updated, even though I see it update in the first request when stepping through the process in the debugger.

**Comment by Tratcher** [comment]
No, requests do not share live session state. The default Session implementation is designed for server clusters so everything is serialized in a central store. When a request arrives the session is retrieved from the store, deserializes it, the app makes changes, and then it's re-serialized back to the store.  When there are two simultaneous requests on the same server or different servers they both retrieve from the store, deserialize, operate on their own copies, and then re-serialize back to the store, potentially overwriting each-others changes. Last write wins. Note that the implementation is also considered coherent; all keys&values are stored together. Even requests operating on different keys may cause conflicts.

**Comment by jltjohanlindqvist** [comment]
I see, thanks. Now the question is what are my alternatives that meet the requirements I stated above? A database or a file storage? Or is there any alternative that uses memory?

**Comment by Tratcher** [comment]
There are no other implementations available, but if you're going to restrict it to a single machine it should be possible to implement ISessionStore and ISession over IMemoryCache such that multiple requests share the same data live. You will need to use read/write locks to avoid corrupting the session though.

**Comment by jltjohanlindqvist** [comment]
Ah, thanks for the great answers!
