### ISSUE TITLE
SessionSample improvements

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Session#130]
[samples/SessionSample/Startup.cs](https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs#L24)
- [ ] Consider removing the SQL connection string. We want to avoid copy/paste and this encourages checking in secrets. At least change the name from `ASPNET5SessionState` to something like `SessionStateCache`
- [ ] add a comment with a fwlink to https://docs.asp.net/en/latest/performance/caching/distributed.html

**Comment by hishamco** [comment]
It's a comment, to give the devs an idea for how to use the SQL Server implementation of `IDistributedCache`, I don't think it's a worth because using SQL Server implementation requires some setup before we use it, but for production I'm agree with you to use the secrets

**Comment by muratg** [comment]
@Rick-Anderson We'd be happy to consider PRs on this. Putting this in the backlog for now because of the heavy workload in many other areas.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2405
