### ISSUE TITLE
DistributedSession with MemoryDistributedCache is unreliable

### ISSUE THREAD

**Issue by frantisekjandos** [aspnet/Session#131]
If DistributedSession uses MemoryDistributedCache, it is unreliable because MemoryDistributedCache uses MemoryCache without CacheItemPriority.NeverRemove option. Then MemoryCache flushes live session not respecting TTL (session idle time interval).
To fix this, both Session and Caching must be modified to set and allow priority when storing the cached item.

**Comment by Tratcher** [comment]
All caches are subject to cache purges, not just MemoryDistributedCache. Session is not designed as a reliable store, that's why it's built on cache.

**Comment by frantisekjandos** [comment]
I am unable to find HTTP session reliability definition :-)
I agree that in case of unauthenticated users, DDoS attack would be very easy if session cannot be expired before idle timeout.
But imagine authenticated user, who needs some time to fill complex form. If authentication is based on session which prematurely expires, user runs into login dialog losing the filled form data.
It would be great if session could be configured to be reliable or not. At least MemoryCache allows it.

**Comment by Tratcher** [comment]
You could still be DDoS'd by authenticated users, think Black Friday.

Is this question theoretical or have you actually had trouble with this on your site? In theory a MemoryCache purge should only happen when your site is under significant memory pressure.

**Comment by frantisekjandos** [comment]
Actually, I have the trouble which I described above. It is single page application and user have to fill more pages using wizard which takes some time. Authentication is based on session. Even the session idle time is set to 30 minutes, user is sometimes asked for reauthentication after 5 minutes, but there seems to be no memory pressure :-(

**Comment by Tratcher** [comment]
Interesting. We should investigate the cache purge trigger: https://github.com/aspnet/Caching/issues/221

**Comment by muratg** [comment]
We'll investigate the issue in Caching.
