### ISSUE TITLE
How to configure expiration time of the cookie

### ISSUE THREAD

**Issue by h56233577** [aspnet/Session#132]
app.UseSession(new SessionOptions()
{
    CookieName = ".AspNetCore.Session",
    IdleTimeout = TimeSpan.FromMinutes(20)
});

The "IdleTimeout" only applies to the content of session, not cookie, how to set the time of cookie?

**Comment by Tratcher** [comment]
Session cookies by definition have no expiration time, they live until the browser session ends.

**Comment by h56233577** [comment]
If I want to store data for several days, does that mean I should use caching and persistent cookies instead of session cookies?

**Comment by hishamco** [comment]
Have a look to the sample specially https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs#L27, https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs#L36

**Comment by Tratcher** [comment]
What kind of data? If you really want the data to stick around for multiple days you should consider putting into a real persistent store like a user database. Persistent cookies are a good way to track users across browser sessions, but you need full user auth to restore lost cookies or move across devices.

**Comment by h56233577** [comment]
I want to store user login status and other information, reduce login times. However, SessionId is not persistent, and can not be customized. If I close the browser, SessionId will be lost, even if I use the database to store data,how to find the user's old data?

**Comment by Tratcher** [comment]
The cookie auth middleware is best for maintaining login status. If you're having trouble with the amount of data stored in the auth cookie you can use the CookieSession store to keep that data cached on the server.
https://github.com/aspnet/Security/blob/dev/samples/CookieSessionSample/Startup.cs

**Comment by h56233577** [comment]
Yes, you are right. But why the "session state middleware" can not set ExpireTimeSpan, it looks very similar to the "cookie middleware"

**Comment by h56233577** [comment]
Sorry, I found their cookie name are different. If I use the same name, what will happen?

**Comment by Tratcher** [comment]
https://en.wikipedia.org/wiki/HTTP_cookie#Session_cookie
"Unlike other cookies, session cookies do not have an expiration date assigned to them, which is how the browser knows to treat them as session cookies."

Don't use the same name for Session and Auth cookies in the same app, they will overwrite eachother and you'll get the wrong behavior. However, if you're moving to an auth cookie you may be able to remove the Session middleware and re-use the cookie name.

**Comment by h56233577** [comment]
thank you, I will use cookie middleware.
