### ISSUE TITLE
Flaky test SessionTests.SessionLogsCacheRefreshException

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Session#136]
Seeing a failure here: http://aspnetci/viewLog.html?buildId=150994&tab=buildResultsDiv&buildTypeId=Releases_Ubuntu1404 though this test has been very inconsistent.

**Comment by hishamco** [comment]
Is this duplicate for #135?

**Comment by JunTaoLuo** [comment]
@hishamco seems like it.

**Comment by hishamco** [comment]
I expect that
