### ISSUE TITLE
Compatibility Issue with AuthenticationServices

### ISSUE THREAD

**Issue by gwicksted** [aspnet/Session#138]
There is an issue where the `Set-Cookie` header contains a value that is not `System.Convert.FromBase64String` compatible generating a warning on every request when the following are configured:
```C#
services.AddAuthentication();
// ...
app.UseCookieAuthentication();
```

Then a controller performs the following:
```C#
await HttpContext.Authentication.SignInAsync("Cookies", cp);
// without an HttpContext.Session.Set("Key", new byte[]{0x15});
```

(thus creating only 1 of 2 potential cookies)

This is the resulting warning:
```
Microsoft.AspNetCore.Session.SessionMiddleware[7]
      Error unprotecting the session cookie.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
```

What's odd is the two session cookies have **different names** so why is `CookieProtection.Unprotect` being invoked against the other cookie?

Notes:
- The auth cookie contains both '-' and '_' making it unsuitable for `System.Convert.FromBase64`.
- It does not matter if data protection is enabled or not.  Only that the Session is **not** created while the Authentication is performed.  If both occur, no warning is generated.
- The warning occurs during subsequent requests following authentication (not during) and continues to do so until either the session is created or the authenticated user is signed out.

**Comment by Tratcher** [comment]
Can you share the raw Cookie and Set-Cookie header values please?

**Comment by gwicksted** [comment]
Ran this with a client:

```C#
response.Headers.TryGetValues("Set-Cookie", out values);
```

Contains two values.  First value:

```
.AspNetCore.Cookies=CfDJ8OS5Gs7NleZBjakhh8OzCRiWzFfMfvOWOtzt0k4mIDqLcucAM42s7bTy3Q7hPAQ5ogZLCAbNE7fq30g4eEMgFsHCcIWimIVmZMf1r328MY93XUIv8RkNzGOMjbu46KXDrafUgvBwpYzepVVtIppLc2hea52eA__xip2cgYqIMxVmrfCReKniptyt0h6InJZHuIW-kSOGUsiNsenS6a0W8nM9w91tdjROIo6NOspZHvQMh-q44b_J_5AfT11E1g9nn2I8ovHpBKwES6Z0JgaUuCeBvLdQtFjVJU1qEG0Iv03t; path=/; httponly
```

Second value:

```
.AspNetCore.Session=CfDJ8OS5Gs7NleZBjakhh8OzCRgFPBeGQVUnYug9PehQ1KpJYvfDRaeaL2psmsziJKZ34D%2FCBtmpMy7DnaYniwVXRf4KAK68M6%2FT0c5l4KABzkQ7NIjw3K%2FW3zAdP2wpCtt57Fk%2BhfyfStyLGW1H7JymyKhnN%2F3UgFMlh23hSnnM8Rrc; path=/; httponly
```

(those are showing the default cookie configurations for path and name)

**Comment by Tratcher** [comment]
And the cookie header from the next request that fails? You can use Fiddler or a network trace to capture this.

**Comment by gwicksted** [comment]
Now it isn't reproducible... so I'm thinking this was my mistake and that I must have had the cookie name set the same in services.AddSession, app.UseCookieAuthentication, and app.UseSession which does cause the warning (and the two implementations are racing to set the value).

I did wipe my history and placed Fiddler in the middle since my initial tests but this looks like a user error!

So it may be worth warning / erroring on startup but, unless I can reproduce this again, there is no issue with the implementation.

**Comment by eddyjl077** [comment]
i am also getting this error in dev mode (vs2015/iis)

Is there anything i can do to resolve it?
