### ISSUE TITLE
DistributedSession.Remove does remove item from underlying IDistributedCache

### ISSUE THREAD

**Issue by jeffrymorris** [aspnet/Session#139]
If you are using a custom IDistributedCache implementation like [CouchbaseCache](https://github.com/couchbaselabs/couchbase-aspnet/blob/3.0-core/src/Couchbase.Extensions.Caching/CouchbaseCache.cs) and you call HttpContext.Session.Remove("somekey"), the session will never be removed from the "cache" because DistributedSession.Remove(..) only removes the key from the in-memory _store, but not the _cache. See [here](https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L154).

Is this by-design or simply missing from the DistributedSession implementation?

**Comment by Tratcher** [comment]
The session is made up of all of the keys and values. Even an empty session is not removed from the cache. We could optimize it here to remove empty sessions https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L238

Note that would cause you to lose the unique session Id.

**Comment by ngonzalezromero** [comment]
so, where is deleted the key from DistributedCache?

**Comment by hishamco** [comment]
@ngonzalezromero have a look to this https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L154

**Comment by ngonzalezromero** [comment]
@hishamco yes, but only remove from _store(IDictionary<EncodedKey, byte[]>) and not from _cache ( IDistributedCache _cache)

**Comment by hishamco** [comment]
This is will remove it from the `MemoryDistributedCache` https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Memory/MemoryDistributedCache.cs#L121

**Comment by Tratcher** [comment]
The SessionMiddleware does not delete sessions from the DistricutedCache, it waits for them to expire.

**Comment by hishamco** [comment]
@Tratcher but I think there's ability to reach the underlying source to remove the key if the case require that

**Comment by jeffrymorris** [comment]
I have spent more time on this and it looks like this may be expected behavior, that perhaps doesn't quite work? The _isModified is set to true when the item its removed from _store, _later_ the [SessionMiddleware](https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionMiddleware.cs) should call ISession.CommitAsync which then would save the contents of _store (which now has the key removed) to the distributed cache since _isModified is true at this point. 

As of now, the CommitAsync is only called when an exception is thrown while calling [_next()](https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionMiddleware.cs#L104-L124).

**Comment by Tratcher** [comment]
@jeffrymorris Finally blocks always execute, with or without an exception.

**Comment by jeffrymorris** [comment]
@Tratcher - yes,  actually misread the code ;)

**Comment by jeffrymorris** [comment]
This is not a bug DistributedSession, but in my underlying IDistributableCache implementation.
