### ISSUE TITLE
Unable to load the session repo projects

### ISSUE THREAD

**Issue by hishamco** [aspnet/Session#14]
After I get the latest changes specially "Update .kproj => .xproj", the VS can't load the projects properly

**Comment by hishamco** [comment]
FYI whenever I modify the solution and change the projects extension to .kproj it works fine, i'm still asking is there any reason for this update kproj -> xproj

**Comment by hishamco** [comment]
I run kvm upgrade to get the dnvm and everything works fine from Power Shell, still i'm working with Sublime integration in windows, and hopefully this issue got fix in the next release of VS

**Comment by Praburaj** [comment]
@hishamco - change from .kproj => .xproj happened only on the dev branch. So VS to load the `.kproj` files will be available in future. Beta3 code lives in master branch. You could try that.
