### ISSUE TITLE
Error unprotecing session cookie when application is ran as a service on CentOS

### ISSUE THREAD

**Issue by jltjohanlindqvist** [aspnet/Session#140]
I have a proxy of sorts where I use the `Microsoft.AspNetCore.Session.SessionMiddleware`. When I run the application normally it works fine and I have no issues, but when I try to run it as a service using systemd I get an error saying `Error unprotecting the session cookie` with the following call stack:

```
System.Security.Cryptography.CryptographicException: The key {ed1be51b-4593-4f30-a08b-8595aeef0fc3} was not found in the key ring.
Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boole
Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
```

Since I couldn't find a way to destroy the session cookie I assume the `SessionMiddleware` is supposed to create a new key if the key wasn't found?

Version: 1.0.0-preview2-003131

**Comment by Tratcher** [comment]
Correct, if the middleware can't read the cookie it will create a new one.
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionMiddleware.cs#L88-L98
Note a new cookie is only sent to the client if the session is modified during that request.
