### ISSUE TITLE
Session Middleware along with Cookie Middleware

### ISSUE THREAD

**Issue by aagarwal10** [aspnet/Session#145]
Hi, I am planning to share authentication cookie between my aspnetcore and my 4.6.1 framework application using documentation from aspnetcore docs. I am using Redis as TicketStore for CookieMiddleware to cache the Authentication ticket

Is it also possible to share session between these two apps?

If yes, how do I order the cookie middleware with session middleware in the pipeline?

Also,  how do I manage the two cookies (one from CookieMiddleware and one from Session Middleware)??

I am very confused....please advise.

**Comment by hishamco** [comment]
I think this is a duplicate for issue #122

**Comment by aagarwal10** [comment]
So based on your reference above, is it still not possible to share session data between two apps in IIS??

**Comment by hishamco** [comment]
AFAIK it's not possible, @Tratcher any idea?

**Comment by Tratcher** [comment]
No, we don't provide any way to interop session data or cookies.
