### ISSUE TITLE
Session Middleware sequence with Cookie Middleware

### ISSUE THREAD

**Issue by aagarwal10** [aspnet/Session#146]
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
            .....	
	    app.UseCookieAuthentication(...)
			
	    app.UseSession()...
	   .....
			
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
}
```
Is this correct order for Session Middleware with Cookie Middleware used with AspNet Identity ??

Thanks

**Comment by hishamco** [comment]
This sample https://github.com/aspnet/Security/tree/dev/samples/CookieSessionSample may helpful for you

**Comment by Tratcher** [comment]
@hishamco that's different. That's what we call "reference mode", or in other words, storing the ClaimsPrincipal on the server and only sending an identifier to the client. Note we do NOT recommend storing it in Session.

@aagarwal10 the order of UseCookieAuthentication and UseSession should not matter, the components are completely unrelated. You just want to put both of them before UseMvc which depends on them.

**Comment by aagarwal10** [comment]
@Tratcher  - is it possible to wire the cookie middleware with session middleware so that if the authentication cookie expires, session can be cleared for a given user logged into the application?

**Comment by Tratcher** [comment]
No, because there's no inherent correlation between user and session. We strongly discourage storing sensitive information in session. If you need to, you should verify the current user identity matches that of the session data on each request.
