### ISSUE TITLE
.net core object to Session without serialize

### ISSUE THREAD

**Issue by idhasitha** [aspnet/Session#152]
0
down vote
favorite
	

i use the .net core `"Microsoft.AspNetCore.Session": "1.0.0"` to use the session in my .net core project and use the extension method witch is mention on MSDN its like this

```
public static void Set<T>(this ISession session, string key, T value)
        {
            session.SetString(key, JsonConvert.SerializeObject(value));
        }
```

In my controller
`
HttpContext.Session.Set<BLL.clsPolicy>("PolicyDATAAPI", policyObj);`

when i pass the object to session this doing the serialization it make the some problems in my object class like : private variables are not serialize like that ,

any way to store object store in session without serialize ? ?

**Comment by hishamco** [comment]
AFAIK you can't do it out of the box, also the serialization will serialize the public members
So that's why I suggest this issue #3 😄

**Comment by JunTaoLuo** [comment]
Session uses a `IDistributedCache` as storage so serialization will always occur.
