### ISSUE TITLE
User getting access to other users session variables

### ISSUE THREAD

**Issue by rbjarnason** [aspnet/Session#157]
We're using DistributedSqlServerCache and in our testing we keep on hitting a very serious problem where two users coming in through IIS, in the same time period, have their sessions mixed up giving them access to each others session variables. We're using .net core 1.0.1.

I've read through the logs to try to find any clues. Googled my way through tons of materials, looking at our configuration but not found anybody with exactly this problem.

Any hints?

**Comment by rbjarnason** [comment]
What I'm currently looking into is that this behavior would maybe happen if the SqlServerCache was not really enabled but using the memory cache that would then be shared depending on which worker process the user was coming in through.  I found that we're doing services.AddMvc(); before services.AddDistributedSqlServerCache(); I'm not sure if that changes anything but next test tomorrow will be doing services.AddMvc(); after adding the cache.

**Comment by hishamco** [comment]
AFAIK the middlewares order is very important

**Comment by hishamco** [comment]
BTW your middleware order should be like this
```csharp
app.UseSession();
app.UseMvc();
```

**Comment by Tratcher** [comment]
The session IDs are GUIDs sent as encrypted cookies to the client. Nothing except bad response caching should cause one user's session cookie to be given to another user. I assume you've verified that these users are coming from different machines, as opposed to one user just signing out and the other signing in via the same browser?

**Comment by rbjarnason** [comment]
Thanks @Tratcher.  Yes, the users are coming from two different companies. This is a highly unusual scenario we discovered because of another unusual bug. The frontend is a single page Polymer/Web Components app.

1. User A logs on and start to continuously do activity in order to trigger this bug.
2. User B send a request to the API, initiates a call to complete the login.
3. User B writes information to the session, a company id
4. User B hits an Crypto/OCSP bug that causes a 15-20 second holdup 
6. User B reads the company id from the session and it gets the wrong company id of User A instead out of the session!
7. User B request completes with an error as a check on our side reveals the inconsistency.
 
So the session does seem to mixup underneath the users in the middle of a single request.

**Comment by Tratcher** [comment]
How readily can you reproduce this? Can you create an independent repro app? 

I'd start with a Fiddler trace from both clients to verify the cookies. Then I'd want to see the server logs for those requests.

Steps 3 and 5 happen on the same request? Session is deserialized into memory for the duration of a request, there shouldn't be any way for another user to affect it, nor even another request from the same user.

**Comment by rbjarnason** [comment]
Yes, Steps 3 and 5 happen on in the same request! I agree the should be no way this would happen, our user code is simple in this regard, just writing and reading from the Session - we have been testing this and trying to work it out for about 3 days until we came here with this problem because of how unbelievable this is but so far we have found nothing in our user code that could be causing this.  We do read and write to the session using a simple SessionUtility that gets added by   services.AddTransient<SessionUtility>();

It is not easy to reproduce but we can do it, we can only reproduce this when the Crypto/OCSP bug happens that hangs up the thread for 15-20 seconds on our external staging servers - which we can do on Monday. I'm not able yet to reproduce this in our dev or internal test server setups.

It's a large app and a very small team so making a independent repro app would take a couple of days with a test rig, but I will create a gist today with our Startup.cs and all the relevant  code snippets and log snippets.

Otherwise my strategy today:
*  Add services.AddMvc();  after services.AddDistributedSqlServerCache(); in Startup.cs (could this really matter?)
* Upgrade the app from 1.0.1 to 1.1

**Comment by rbjarnason** [comment]
Ah, maybe its AddTransient config - looking into it now...

**Comment by rbjarnason** [comment]
@Tratcher I think AddTransient is what we want but here is a gist with the relevant code and log Session log snippets from a case when this was reproduced - there are probably more than two people actually testing - this has gone into full external testing with a group of our customers.

**Comment by rbjarnason** [comment]
One thing I noticed. Those three messages appear in the same seconds as when the mixup happens and its starts with key 8fd with count 1, then f8f with count 11, then again 8fd with count of 12, which is strange and could be a coincidence but why is second 8fd not 2 - it could seem that 8fd is picking up from count 11 from the other key.

2017-03-31 11:41:19.3001|4|Microsoft.AspNetCore.Session.DistributedSession|DEBUG|Session loaded; Key:8fd76c42-6cc8-e6aa-a54f-69756806a578, Id:9c3022ae-ebc8-a4b4-ef9e-9b501b03c05e, Count:1 
2017-03-31 11:41:21.5308|5|Microsoft.AspNetCore.Session.DistributedSession|DEBUG|Session stored; Key:f8f50903-3c63-1ef9-adb5-03d2fc340de3, Id:a53f5a4f-bc3d-c2cc-0d16-41eab368d565, Count:11 
2017-03-31 11:41:23.6835|5|Microsoft.AspNetCore.Session.DistributedSession|DEBUG|Session stored; Key:8fd76c42-6cc8-e6aa-a54f-69756806a578, Id:9c3022ae-ebc8-a4b4-ef9e-9b501b03c05e, Count:12

**Comment by rbjarnason** [comment]
I see after reading the code that Count is really a count of the objects in the session so maybe this count action is normal.

**Comment by rbjarnason** [comment]
We upgraded to 1.1.0 but we still managed to reproduce the problem.

Just before the mixup with user A we get the following session read from user B coming in from another company - after this user A has all the session information from user B:
2017-04-07 16:00:32.5866||Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector|TRACE|Performing unprotect operation to key {85d51abc-3f6f-4ebb-a3f7-204b91c1e646} with purposes ('osk2', 'SessionMiddleware').
2017-04-07 16:00:32.5866||Microsoft.AspNetCore.Session.DistributedSession|DEBUG|Session loaded; Key:b66c92ab-1bd2-a1fb-e317-ede5733ed0ec, Id:c86c915e-8732-c187-928f-d4c334ecd514, Count:14

Not sure if the "unprotected" is relevant there - we're looking into if the issue could be from the outside, for example something load balancer related or database related?

@Tratcher Any hints or ideas on what to test would be appreciated! :)

**Comment by rbjarnason** [comment]
@Tratcher We have most likely found the bug, we will continue to test today and if it is not replicated I will close this ticket.

1. We had a AuthAttribute utility class that came over from the former .net framework version that defined a static attribute to temporarily hold the session interface - a pattern from .net framework. The session interface was passed in fresh on each call to the given function but a situation arose where both User A and User B were in the middle of the same function at the same time.
2. Our broken crypto function was/is actually making network calls in its 16-22 sec loop.
3. Kestrel seems to works async for network calls even if our user code is not async. This allowed user A to access to the static session of User B after User A came back from the async crypto network loop.

We fixed this by instantiating the AuthAttribute utility class so nothing is defined static.

**Comment by rbjarnason** [comment]
Confirmed fixed :)
