### ISSUE TITLE
Make it easier to load session async

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Session#158]
ISession does not have a good way to indicate if it has been loaded yet, and all of the properties and methods will do a lazy synchronous load. The only way to be sure you load it async is to call LoadAsync before any usage (since you're not sure if anyone loaded it before you).

@DamianEdwards has proposed removing the lazy sync loads and throwing if LoadAsync has not been called.

Some ideas to make LoadAsync easier:
- Have an IsLoaded flag
- Have a LoadSession attribute and an MVC filter that can be used to pre-load session for specific controllers/actions.

**Comment by muratg** [comment]
What's `ISession`? Did you mean `ISessionStore` or `DistributedSession` instead?

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Features/ISession.cs, as returned by HttpContext.Session. DistributedSession implements ISession.

**Comment by muratg** [comment]
Ah, got it. :+1:

**Comment by Tratcher** [comment]
@muratg triage for 2.0? This includes some breaking changes.

**Comment by muratg** [comment]
@Tratcher Assigning to 2.0.0 because of the possibility of breaking changes. If we can't get to it, we'll move out.

**Comment by Tratcher** [comment]
@DamianEdwards @davidfowl this would be a hard break for [SessionStateTempDataProvider](https://github.com/aspnet/Mvc/blob/89bd6dc1cd188772f9b85eb75ec0d79506a3bf2f/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/SessionStateTempDataProvider.cs#L14) without a mitigation like an MVC session loading filter/attribute.

**Comment by Tratcher** [comment]
I think adding the MVC filter is the best we can do here without major usability regressions. I'll file a separate MVC work item.

**Comment by muratg** [comment]
Will do https://github.com/aspnet/Mvc/issues/6463 instead.
