### ISSUE TITLE
Issue: Session Middleware with Redis Distributed Caching not working in web farm

### ISSUE THREAD

**Issue by aagarwal10** [aspnet/Session#159]
Hi I am using Session Middleware with Redis as the session store in a web farm scenario (2 servers for testing). I use F5 for load balancing my web servers. I use F5 in production and staging too. 

I am setting session with a value in one controller action and reading the same session variable in another controller action.

I am running into a weird scenario, where the server instance that wrote to the store is only able to read the value, the other server is showing null value even though Redis does show the value present in its db

Redis server is hosted on a single server 
Tested that both web servers can access Redis Server Remotely with no auth successfully.
Comment the "bind" in redis.windows-service.conf file.

I have confirmed that same code is deployed to both the web servers.

Here is my code snippets for configuring Session Middleware with Redis

```
services.AddDistributedRedisCache(options =>
            {
                options.InstanceName = "RedisSessionStore";
                options.Configuration = $"{redisInstanceName}:6379";      });
```

```
services.AddSession(options =>
            {
                options.CookieName = "Session.Cookie.Core";
            });
```

```
app.UseSession();

app.UseMvc()...
```

```
public IActionResult About()
        {
            ViewData["SessionData"] = HttpContext.Session.GetString("SessionTestKey");

            return View();
        }

    public IActionResult Contact()
        {
            HttpContext.Session.SetString("SessionTestKey", "Hello World");

            return View();
        }
```
Now my question is -what do I need to do more to make session work in web farm scenario? Am I missing something or is there a bug in Session Middleware ?

Please help.

Thanks a lot

**Comment by Tratcher** [comment]
My first guess is that you don't have DataProtection set up for your server farm, so session can't even read the protected cookie on the second machine.
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction
http://www.paraesthesia.com/archive/2016/06/15/set-up-asp-net-dataprotection-in-a-farm/

**Comment by aagarwal10** [comment]
@Tratcher  - Your guess makes sense, because I had to setup Shared Dataprotection for my cookie middleware for my server farm. 

However, I am not seeing any option to pass DataprotectionProvider specific to Session into Session Middleware when calling app.UseSession similar to Cookie Middleware does  ?

The link you provided to does that on global level and not scoped to Session Middleware. 

Do you think Session Middleware should have property on "SessionOptions" to allow client app to pass the DataProtectionProvider into SessionMiddleware?

Please suggest.

Thanks a lot

**Comment by Tratcher** [comment]
It could have a local data protection provider. Why can't you use the global one?

**Comment by aagarwal10** [comment]
I can certainly do with global one but was wondering whether design of Session Options be consistent with Cookie Options in Cookie Middleware?

**Comment by Tratcher** [comment]
For reference, cookies had the dataprotection instance option before the global one was available (3-4 years ago).  Session was more recently developed.

**Comment by aagarwal10** [comment]
I feel at least the documentation should be updated to reflect changes needed to make Session Middleware work in a web farm scenario. 

Thanks for your help.

**Comment by Tratcher** [comment]
Agreed

**Comment by Tratcher** [comment]
https://github.com/aspnet/Docs/issues/3255
