### ISSUE TITLE
Spurious log messages

### ISSUE THREAD

**Issue by mguinness** [aspnet/Session#160]
I'm using session storage in my app primarily for TempData, but I'm noticing several "Accessing expired session" warnings in my logs which is being generated in [LoggingExtensions](https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/LoggingExtensions.cs#L26-L27).

It seems that the message is somewhat misleading.  Would something like "Expired session unavailable" be better than "Accessing expired session"?  The latter seems contradictory.  Also, why would this be a warning and not a debug message?  It seems that this would increase noise to signal for logs filtered to warning.

**Comment by muratg** [comment]
Agreed that the message can be clearer. @glennc What's your thoughts on what the log level for this message to be?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2404
