### ISSUE TITLE
Make Session loading (Deserialize) faster

### ISSUE THREAD

**Issue by sdrapkin** [aspnet/Session#163]
[DistributedSession.cs](https://github.com/aspnet/Session/blob/02b975c59776722c0cc47542599a59bef9445440/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L294) adds deserialized property values in a loop to a `Dictionary<EncodedKey, byte[]> _store`.

This causes continuous dictionary resizing (which uses prime-number capacities). However, this resizing is wasteful, since `Deserialize()` already knows the required capacity (`expectedEntries`).

`_store` should be initialised with a known capacity inside `Deserialize()`, instead if being initialised with an unknown capacity inside ctor.

**Comment by muratg** [comment]
@sdrapkin Would you be interested in sending a PR?

**Comment by sdrapkin** [comment]
@muratg No (didn't sign CLA, and the change is trivial).

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2403
