### ISSUE TITLE
Session options IdleTimeout is not working

### ISSUE THREAD

**Issue by hstarorg** [aspnet/Session#169]
I used the code: 
```
services.AddSession(options =>
{
    options.CookieHttpOnly = true;
    options.IdleTimeout = TimeSpan.FromDays(7);
});
```
But session cookie Expires always `session`, not the time after 7 days.

**Comment by lon-yang** [comment]
Same problem. 
Is any way to set cookie's expire time at https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionMiddleware.cs#L153-L168 ?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Session/issues/132
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionOptions.cs#L45-L46

**Comment by hstarorg** [comment]
Would you tell us, how to set the session cookie timeout? Very thanks. We are using .Net core 2.0 preview.

**Comment by Tratcher** [comment]
The session cookie by definition has no timeout, it lasts for the lifetime of the browser session. The IdleTimeout lets you control how long data persists on your server which is the only aspect it is ever possible for you to maintain control over.

**Comment by hstarorg** [comment]
Very thanks~
