### ISSUE TITLE
Replace UseSession(SessionOptions) with UseSession(Action<SessionOptions>)

### ISSUE THREAD

**Issue by HaoK** [aspnet/Session#174]
Since the session middleware is using IOptions, we should mirror how we normally configure options...  It should instead always use IOptions and apply the action to it afterwards (basically a PostPostConfigureOptions)

We should revisit any other middleware that are using this pattern and using IOptions

`UseSession(new SessionOptions())` => `UseSession(o => { })`

**Comment by muratg** [comment]
@HaoK is this still a valid issue?  Are we going to do this?

**Comment by HaoK** [comment]
Its a consistency issue, but I'm not sure this is something we could change in a minor release (breaking changes and all)

**Comment by Tratcher** [comment]
We could add the new one.

**Comment by HaoK** [comment]
Yeah we could add that across the board, `UseXyz(o => { })` everywhere that's currently only taking `UseXyz(new XyzOptions())`

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2402
