### ISSUE TITLE
Remove obsolete options APIs

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Session#175]
Follow-up to https://github.com/aspnet/Session/pull/173

Remove the following obsolete APIs
```
SessionOptions
  .CookieName 
  .CookiePath
  .CookieDomain
  .CookieHttpOnly
  .CookieSecure 
```
~~.SameSideMode~~ already removed.

**Comment by Tratcher** [comment]
SameSiteMode was new in this release and can just be removed, no need to obsolete it.
________________________________

**Comment by natemcmaster** [comment]
Good catch. PR to remove it for 2.0.0 https://github.com/aspnet/Session/pull/176

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2401
