### ISSUE TITLE
Update session to configure DistributedMemoryCache options by default

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Session#177]
Once https://github.com/aspnet/Caching/issues/329 is addressed, session needs to add a default value for the maximum cache size.

**Comment by muratg** [comment]
@JunTaoLuo is this valid with the new plan?

**Comment by muratg** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
No changes are required for Session, it will happen in caching.
