### ISSUE TITLE
Any plans for maximum session size property?

### ISSUE THREAD

**Issue by wysisoft** [aspnet/Session#185]
Are there any plans for a property that sets a maximum size for total user session, and throws an exception if its exceeded? Any recommendations on how I can simply accomplish this? (currently using redis distributed cache)

**Comment by Tratcher** [comment]
No plans for this yet, but it's an interesting idea.

Some workarounds:
- You have full access to the data from ISession so it would not be difficult to enforce your own limit via a helper method, middleware, etc.. e.g. enumerate the session and total the size of the elements.
- It should not be hard to copy and override the ISessionStore implementation to enforce this. 
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionServiceCollectionExtensions.cs#L27

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2398
