### ISSUE TITLE
cant access Session in other API

### ISSUE THREAD

**Issue by meninjanho4788** [aspnet/Session#190]
I use netcore, i have two API, one API Set Session value HttpContext.Session.SetString("GoogleProvider", info.ProviderKey);

And one API get this session but result is null. HttpContext.Session.GetString("GoogleProvider");

**Comment by Tratcher** [comment]
That's a bit vague. Are these two different Actions, Controllers, or completely separate applications?

**Comment by meninjanho4788** [comment]
Yes, i have two controller : AccountController(api/account/registry) is set Session and AuthorizationController(connect/token) is get Session,

**Comment by meninjanho4788** [comment]
My code : 
AccountController
[HttpGet("ExternalLoginCallback")]
    [AllowAnonymous]
    public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
    {  ....
HttpContext.Session.SetString("MySession", info.ProviderKey);
...
}

AuthorizationController :
[HttpPost("~/connect/token"), Produces("application/json")]
    [AllowAnonymous]
    public async Task<IActionResult> Exchange(OpenIdConnectRequest request)
    {
var dataSession = HttpContext.Session.GetString("MySession");
//dataSession is null
}

**Comment by meninjanho4788** [comment]
My Setting in Status.cs :  
services.AddDistributedMemoryCache();
public void ConfigureServices(IServiceCollection services)
{
      services.AddMemoryCache();
      services.AddSession();
}
public void Configure(IApplicationBuilder app)
    {
app.UseSession();
app.UseMvc(routes =>
      {
        routes.MapSpaFallbackRoute( name: "spa-fallback",  defaults: new { controller = "Home", action = "Index" });
      });
}

**Comment by meninjanho4788** [comment]
Many thank you. I need n't use session in API because it will make my application vulnerable to this class of attack. I will try other way.
