### ISSUE TITLE
[Patch 2.0.x] Downgrade cancellation logs

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Session#194]
We've gotten several complaints that session overlogs cancellation exceptions caused by client disconnects. These can be downgraded in severity and verbosity.

This is a backport of https://github.com/aspnet/Session/issues/189.

@muratg @Eilon

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon
