### ISSUE TITLE
Session OnStart and Session OnEnd

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Session#206]
_From @ErcinDedeoglu on January 7, 2018 20:59_

I came here from https://github.com/aspnet/Session/issues/20

@Tratcher @davidfowl @muratg
If you are not going to implement session onend; why we're setting the sessiontimeout?
I read all of above, but not implementing sesion onend is really strange decision. Every application uses session events. Also @Tratcher adviced that we can store data on sql not session. This is also not acceptable...

My issue is I need session start event to recognize user from its cookie to auto login. But I cant handle session start atm...
  

_Copied from original issue: dotnet/corefx#26212_

**Comment by Tratcher** [comment]
_From @karelz on January 7, 2018 21:15_

@ErcinDedeoglu what exactly do you need in CoreFX? What kind of API on which type?
AFAIK Session is ASP.NET API, not in CoreFX ...

**Comment by Tratcher** [comment]
The timeout is a setting provided to the cache. Because it's a distributed cache there's no observable event when the timeout expires.

Auto login? Session and authentication should not be mixed. Session is a browser session, not a user session. Can you be more specific about what you're trying to achieve?

**Comment by ErcinDedeoglu** [comment]
Dear @Tratcher,
Migrating MVC4 to AspNetCore MVC.
Old system is local and not really cloud. And it'll stay as local.

Old system recognize user from Cookie (aka remember me feature) on Global.asax => Session_Start()
And assing UserID from database to System.Web.HttpContext.Current.Session["UserID"]
Later code can understand and recognize the "Browser" User from Session["UserID"].

Could you help me to solve this scenario please?

**Comment by Tratcher** [comment]
And by local you mean it's on a single machine? We avoid features that only work on a single machine, you get locked in and can't scale.

You can do this with the auth cookie, you don't need the session cookie.
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x
Not that the 'remember me' feature maps to IsPersistent 
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x#persistent-cookies

**Comment by ErcinDedeoglu** [comment]
Thank you very much @Tratcher 
Most of time you dont need to scale it. We're not programming dedicated/cloud server-side applications only.

By the way i solved it by writing code in middleware. I'm checking session on middleware and try to get cookie on it.

Also I don't want to use authentication things provided by Microsoft. In my opinion you should give free world to coder. :) Coder can solve it when needs to scale.
*By the way, before came and create issue, I searched a lot over internet about session_start/end on net core.
Ppl want it.

Thanks a gain 👍

**Comment by leak** [comment]
I do have a use case for this: Licensing

Basically there is a floating license pool and licenses are handed out on per session basis. It cannot be done on Identity user basis otherwise customers might just use the same user everywhere. Doing this by session 
 allows decent user comfort, e.g. opening multiple tabs without consuming multiple user licenses, etc.

The tricky part is returning licenses back to the pool when a user just closes the browser without logging out properly and this is where Session OnEnd in conjunction with its timeout would help a lot.

This used to be part of the session system and now it isn't anymore. To me this is a step backwards.

**Comment by Tratcher** [comment]
The old system's OnEnd was quite unreliable in a distributed environment, and even it couldn't detect browser close, only cache expiration. For a scenario like this you'd be better off tracking the license expiration directly. E.g. return the license if it's not used for x minutes, where x is greater than your default session timeout.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#3025
