### ISSUE TITLE
How to get number of session

### ISSUE THREAD

**Issue by lillo42** [aspnet/Session#211]
Hi,

How can I get number of session ?

**Comment by Tratcher** [comment]
The number of concurrent sessions stored in the distributed cache? That information is not available through an API. You'd have to examine the distributed cache directly and see how many entries it had.

**Comment by lillo42** [comment]
In my case, I will have just 1 server.

What I need to do to examine the distributed cache directly ? Do you have some example?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#3024
