### ISSUE TITLE
How to add a custom session in .net core?

### ISSUE THREAD

**Issue by mgolois** [aspnet/Session#216]
I created a CustomDistributedSession that implements ISession.
How to do I tell my web application to use my version instead of the default DistributedSession class?

Thanks!

**Comment by Tratcher** [comment]
Did you register it in DI?
https://github.com/aspnet/Session/blob/c01b50fa0c79daf72509e4a917022d12b4fc7e21/src/Microsoft.AspNetCore.Session/SessionServiceCollectionExtensions.cs#L28

Out of curiosity, what did you customize?

**Comment by mgolois** [comment]
Thanks, @Tratcher , I was able to find that.
I had a question from one dev regarding adding object to session state. I was trying to create a custom one that allows that, so that the consumer won't have to worry about converting object to json everytime.
Also they have existing application (asp.net 4) that was taking advantage of the reference type:
```
 Session["student"] = student;
 student.Grade = "90";
```
Because of the reference type, my session Student will have the updated grade. I don't have to do a JsonConvert to update the student. In the default session State middleware, I will have to call Session set() twice

**Comment by mgolois** [comment]
@Tratcher, I got your point, but in this case everything stored in the session from the legacy application was serializable. Using the default option will require additional refactor. Thanks!
