### ISSUE TITLE
Session.Cancel()

### ISSUE THREAD

**Issue by hishamco** [aspnet/Session#27]
Can we have a way to cancel the current session, something looks like ```Session.Abandon()```. This may related to the issue #20 because it should fire a onEnd event

**Comment by Tratcher** [comment]
What precisely would you want cancel to do?  Discard the data? Delete the cookie?

**Comment by hishamco** [comment]
@Tratcher i.e. destroy the session, because ```Session.Clear()``` will remove all the objects stored in a session, but the session will be destroyed when the session times out.

Have a look to https://msdn.microsoft.com/en-us/library/system.web.sessionstate.httpsessionstate.abandon%28v=vs.110%29.aspx

**Comment by Tratcher** [comment]
So you're asking for Cancel() to delete the session from storage (wherever that may be).

There is very little difference between an empty session and a non-existent session from the storage perspective. In fact, I could optimize the storage logic to ignore/discard empty sessions entirely ([right here?](https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNet.Session/DistributedSession.cs#L123)). That would make session.Clear() equivalent to session.Cancel().

**Comment by hishamco** [comment]
@Tratcher I thought that ```Session.Clear()``` removes all the objects stored in a session but not destroy the session. Thanks for your clarification
