### ISSUE TITLE
Session Cookie Expiration

### ISSUE THREAD

**Issue by stephenjwatkins** [aspnet/Session#29]
It doesn't appear possible to set cookie expiration for a session. So, as you know, when the browser is restarted, the session is gone. This prevents the possibility of implementing "remember me"-like functionality. Are there plans to include session cookie expiration into the session package, or perhaps I am missing something as it is?

**Comment by Tratcher** [comment]
Isn't "Remember Me" usually for auth cookies?  Session and auth are very different concepts. Session is designed a transitory cache. Anything you want to persist should be associated with a user account in permanent storage.

**Comment by stephenjwatkins** [comment]
Yeah, I suppose you're right. I'm used to being able to configure the session cookie expiration in frameworks such as express and rails.

I was attempting to use sessions for storing some information about anonymous users that would hopefully be persisted longer than just the browser session. I do realize that goes against the idea of sessions and so I am probably using the wrong storage technique here.

I appreciate the clarification.
