### ISSUE TITLE
'Refresh' the session even when its not accessed in current request

### ISSUE THREAD

**Issue by kichalla** [aspnet/Session#41]
Data of a session should be alive even when user does not 'access' the data but is still actively communicating with different parts of the application. So call refresh the session if not modified here
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNet.Session/DistributedSession.cs#L121

/cc: @Tratcher 

@muratg : I think we should do this for Beta6

**Comment by muratg** [comment]
@kichalla Not sure if I understand the scenario here. The code seems to be executed when we try to commit the data and only updated if it's locally modified.  Is there something broken?

**Comment by kichalla** [comment]
@muratg No, nothing is broken and looks like this bug existed since the beginning. Following is an example of the scenario:
- Request 1 hit action Home/Index which stored some data in Session.(Here when response is going out, we commit or save the serialized data)
- After some time request 2 hit action Home/Contact which doesn't do anything with Session data.(Here even though the user did not modify any session data, we need to refresh the Session so that the sliding expiration keeps extending)

**Comment by muratg** [comment]
Got it, thanks!  @Tratcher what are your thoughts on this? What are the conventions in other Session implementations about this?

**Comment by Tratcher** [comment]
I recommended it. I don't have much insight into other platforms, but it couldn't hurt to do a little more research @kichalla.

**Comment by kichalla** [comment]
Commit d9b136e20d9709fd2f801ce57aee75bbaa0d3236
