### ISSUE TITLE
must we swallow an error if session is not configured?

### ISSUE THREAD

**Issue by joeaudette** [aspnet/Session#42]
I'm using an extension method on controller to set alerts using TempData which in turn depends on session, code for the method is as follows:

    private static void AddAlert(
            this Controller controller,
            string alertStyle,
            string message,
            bool dismissable)
        {
            try
            {
                if(controller.Context.Session != null)
                {    
                    var alerts = controller.TempData.ContainsKey(Alert.TempDataKey)
                    ? (List<Alert>)controller.TempData[Alert.TempDataKey]
                    : new List<Alert>();

                    alerts.Add(new Alert
                    {
                        AlertStyle = alertStyle,
                        Message = message,
                        Dismissable = dismissable
                    });

                    controller.TempData[Alert.TempDataKey] = alerts;
                }

            }
            catch(InvalidOperationException)
            {
                // happens if session is not configured
                // TempData depends on session
            }
            
        }

I don't like it that it I'm having to catch System.InvalidOperationException even though I'm checking if session is null. If I remove the check for null the error is not stopped by the try catch so it completely breaks the app if session is not configured. Adding the null check somehow made it possible to catch the exception.
Of course I can fix it by enabling session, but my code is in a library that I expect others to use and I don't want to force them to enable session if they don't want to. If they don't enable session I want the alerts feature to fail silently, it will be documented that to use it session must be enabled. But in that scenario I'm forced to keep swallowing the exception which seems undesirable.

Is there any way to detect if session is available without raising an exception?

**Comment by Tratcher** [comment]
Try: `if (controller.Context.GetFeature<ISessionFeature>() != null)`

**Comment by joeaudette** [comment]
That works great! I was able to remove the try catch.
Thanks for the amazingly fast response with the answer!

**Comment by Tratcher** [comment]
Welcome.
