### ISSUE TITLE
Bug while executing 'install-sqlservercache' command

### ISSUE THREAD

**Issue by hishamco** [aspnet/Session#50]
I already uncomment the lines to use the Microsoft SQL Server implementation of ```IDistributedCache```, but whenever I execute the **dnx . install-sqlservercache** command error show up in the command line

**Comment by kichalla** [comment]
@hishamco ...follow the steps below and see if you still see the issue:

- Run `dnu commands install Microsoft.Framework.Caching.SqlServer.SqlConfig` to install the 'global' command called `sqlservercache`.
- Run `sqlservercache <connectionstring-to-database> <schema-name> <table-name>` to set up the table and indexes.
- Register this cache in DI. Example:
```c#
services.AddSqlServerCache(o =>
{
    o.ConnectionString = "Server=localhost;Database=SessionSampleDb;Trusted_Connection=True;";
    o.SchemaName = "dbo";
    o.TableName = "SessionSample";
});
```

**Comment by muratg** [comment]
@hishamco Closing this one.  If @kichalla's instructions do not work, feel free to re-open :)

**Comment by hishamco** [comment]
Thanks @kichalla I'd like to inform you that the first step produce **unable to locate the package Microsoft.Framework.Caching.SqlServer.SqlConfig**

**Comment by hishamco** [comment]
@kichalla any idea about the error

**Comment by kichalla** [comment]
My bad, the package name is `Microsoft.Framework.Caching.SqlConfig` (notice that there is no SqlServer in it)

**Comment by hishamco** [comment]
I got ```ArgumentNullException``` paramter **path1**, please reopen the issue until it got fix

**Comment by kichalla** [comment]
@hishamco can you show the entire command that you are trying?

**Comment by hishamco** [comment]
Here is the command ```dnu commands install Microsoft.Framework.Caching.SqlConfig``` as you told me before

**Comment by muratg** [comment]
Activating for further investigation

**Comment by kichalla** [comment]
@hishamco I am unable to repro the issue that you are seeing

My DNU version is Microsoft .NET Development Utility CLR-x86-1.0.0-beta6-12232

Feeds used:
    https://www.myget.org/F/aspnetvnext/api/v2/
    https://www.nuget.org/api/v2/

**Comment by kichalla** [comment]
Also to isolate the issue, can you verify if you are able install another package having a global command..example:
`dnu commands install Microsoft.Framework.SecretManager`

**Comment by hishamco** [comment]
Finally the command executed successfully after upgrade dnvm to the version that you mentioned before, but still i'm facing an issue during executing ```sqlservercache``` command, I passed the connectionString, schema and table like what you mentioned before, but unrecognized argument error occurs in ConnectionString

**Comment by kichalla** [comment]
try this `sqlservercache create <connectionstring-to-database> <schema-name> <table-name>`

**Comment by hishamco** [comment]
I executed this ```sqlservercache create "server=.;database=myDB;integrated security=true" dbo Sessions```, again error occurs "Format of initialization string does not conform to specification starting at index 23"

**Comment by kichalla** [comment]
I cannot repro your issue using the above command against my SQL Server 2012 server. Not sure if its specific to your sql server version, but this seems like an error with connection string: http://stackoverflow.com/questions/8243008/format-of-the-initialization-string-does-not-conform-to-specification-starting-a

**Comment by hishamco** [comment]
Thanks @kichalla it works fine when i used **Trusted_Connection** instead of **Integrated Security**, but when I run the sample there's no entries show up in the table

**Comment by kichalla** [comment]
Thanks @hishamco ...the instructions in the sample were incorrect...can you try with the updated instructions now: https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs#L23-L44

**Comment by hishamco** [comment]
Still the table is not updated anymore!!

**Comment by kichalla** [comment]
@hishamco Can you share your code?

**Comment by hishamco** [comment]
Finally .. it works fine, and thanks for your collaboration :smile:
