### ISSUE TITLE
Session issue in Chrome

### ISSUE THREAD

**Issue by hishamco** [aspnet/Session#51]
I notice from couple months ago a strange behavior while I run the sample in Chrome browser, the **visits** session increment by two instead of one!! I upgrade the Chrome today, but the same behavior occurs, i'm not sure what causes this bug

**Comment by Tratcher** [comment]
If you open Fiddler or look at the request paths on the server you'll often see the browser make two requests. One request is for the page you actually asked for (http://localhost/) and the other is for the icon that goes on the tab next to the title (http://localhost/favicon.ico).

**Comment by hishamco** [comment]
You are right @Tratcher strange I don't know why this happen in Chrome only!!
