### ISSUE TITLE
React to System.Security.Cryptography.* changes in CoreFX

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Session#54]
https://github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c

![image](https://cloud.githubusercontent.com/assets/6998306/9151283/543630a0-3dfd-11e5-9d66-d5b3e0d73dbd.png)

/cc @Tratcher

**Comment by hishamco** [comment]
I have seen ```SessionMiddleware``` that uses ```System.Security.Cryptography``` if there's a change you can submit a PR

**Comment by PinpointTownes** [comment]
@Tratcher sounds like you missed this one :smile:

**Comment by PinpointTownes** [comment]
Thanks! :+1:
