### ISSUE TITLE
Is it possible yet to use Redis as backing for Session?

### ISSUE THREAD

**Issue by chassq** [aspnet/Session#56]
I looked at the current sample code for Distributed Cache for Session State using Redis. It was not clear to me where we configure the RedisCache connection information. Anyone know?

**Comment by hishamco** [comment]
Have a look to this https://github.com/aspnet/Caching/blob/dev/samples/RedisCacheSample/Program.cs#L27

**Comment by chassq** [comment]
Saw this but where does the connection string go. Configuration or Instance? Do we need to specify instance?

**Comment by hishamco** [comment]
The ```Connect``` method https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Caching.Redis/RedisCache.cs#L46 and ```ConnectAsync``` https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Caching.Redis/RedisCache.cs#L55 are called in ```GetAndRefresh``` & ```Set``` methods behind the scenes
Regarding the ```instance``` this line https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Caching.Redis/RedisCache.cs#L43 is enough to answer your question

**Comment by chassq** [comment]
Thanks! That helped. I have a better understanding now.
