### ISSUE TITLE
IHttpContextAccessor is must for random class?

### ISSUE THREAD

**Issue by NeelBhatt** [aspnet/Session#57]
As far as i know if we want to implement Session in any normal class which is not a controller we can access the HttpContext by injecting IHttpContextAccessor.

So like:
```
private readonly IHttpContextAccessor _httpContextAccessor;

public SessionUtility(IHttpContextAccessor httpContextAccessor)
{
    _httpContextAccessor = httpContextAccessor;
}
```

I would like to know if there is any default wrapper is made for this or it is final implementation?

Reason for this is to update it in my Post which is here: https://neelbhatt40.wordpress.com/2015/09/07/implement-sessions-in-asp-net-5vnext-and-mvc-6/

**Comment by davidfowl** [comment]
> I would like to know if there is any default wrapper is made for this or it is final implementation?

What do you mean? There is no default wrapper and there's no `HttpContext.Current`. `IHttpContextAccessor` is the way to access the current `HttpContext` outside of passing it around explicitly.

**Comment by NeelBhatt** [comment]
I know there is not any HttpContext.Current for normal class.

I wanted to know if there is anything like SessionUtility which does all Session related operations!

Anyways thanks i got the answer :+1:

**Comment by davidfowl** [comment]
Nope!
