### ISSUE TITLE
Better session security? 

### ISSUE THREAD

**Issue by alexdresko** [aspnet/Session#68]
I'm curious why the session management system still doesn't implement something more secure like what is discussed http://www.dotnetnoob.com/2013/07/ramping-up-aspnet-session-security.html in great detail. 

Is there something intrinsically wrong with the techniques outlined in that post? I ask out of ignorance, as someone who is looking to build a system with strong security in place.

**Comment by Tratcher** [comment]
@blowdart?

**Comment by blowdart** [comment]
I am about to hop on a plane, and will be slow to respond all week.

So, quickly

1) We don't support session ID in URLs any more. So the session fixation problem goes away.
2) As noted auth is separate to session
3) Protecting against XSS is the app's concern, but, with MVC we encode everything by default. So, setting the cookie via XSS is unlikely, unless the developer has bypassed all our protection, at which point there's no helping them.
4) Man in the middle attacks - use HTTPS

If you want Andre's protection then by all means add his package, but I don't see the need to implement that sort of approach ourselves.

**Comment by muratg** [comment]
Closing based on @blowdart's comment. @alexdresko, please let us know if you have other questions.
