### ISSUE TITLE
Session renames in Beta 8?

### ISSUE THREAD

**Issue by NeelBhatt** [aspnet/Session#69]
Are there any changes in Sessions like, 

Previously it was:

```Context.Session.Set(String, byte[])```

and in beta 8 it is:

```HttpContext.Session.SetInt32(String, byte[])```

as shown here:

https://christopherhackett.co.uk/blog/2015/10/17/ASP.NET-5-MVC-6-renames-in-beta-8/

Though I tried to search but I am not sure about this change!

**Comment by Eilon** [comment]
The `Context` -> `HttpContext` change is an MVC change to restore the MVC 5 name.
