### ISSUE TITLE
Session write concurrency 

### ISSUE THREAD

**Issue by andyedinborough** [aspnet/Session#72]
Is there any concern about how this implementation doesn't appear to allow for concurrent write access to session data?  If request A starts and reads from session, then request B starts, reads, and writes to session, and then request A writes to session and finishes, then the data data written by B is lost -- even if it's a different session variable that request B used.

While I love the fact that requests are not locked to maintain session integrity, there must be a way to maintain for concurrent requests to safely update the session.  Could there be some change tracking added?

**Comment by Tratcher** [comment]
Already discussed here: https://github.com/aspnet/Session/issues/60

**Comment by andyedinborough** [comment]
Ah, thanks!
