### ISSUE TITLE
dnxcore 50 support

### ISSUE THREAD

**Issue by ahmad-moussawi** [aspnet/Session#73]
Is there a plan to support the dnxcore50 ?

**Comment by Tratcher** [comment]
dotnet5.4 already works with dnxcore50.

**Comment by ahmad-moussawi** [comment]
I update my project.json to target the `netcore54` but am still getting that:
```
The dependency Microsoft.Aspnet.Session 1.0.0-rc1-final in project does not support framework .NetCore,Version=5.4
```

I am doing something wrong ?

**Comment by Tratcher** [comment]
Applications should still target dnxcore50. It works fine in the VS templates. Are you adding it to an app or a class library?
