### ISSUE TITLE
Installing the Session package cause errors in the Application

### ISSUE THREAD

**Issue by ahmad-moussawi** [aspnet/Session#74]
After Installing the package on a new project, I get the following errors

error|file
-----|----
CS0012 The type 'AuthenticationProperties' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNet.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. tx.DNX 4.5.1 | Controllers\AccountController.cs	147
CS0012 The type 'HttpContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNet.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. tx.DNX 4.5.1 | Controllers\AccountController.cs	460
CS0266 Cannot implicitly convert type 'System.Collections.Generic.List<Microsoft.AspNet.Http.Authentication.AuthenticationDescription>' to 'System.Collections.Generic.IList<Microsoft.AspNet.Http.Authentication.AuthenticationDescription>'. An explicit conversion exists (are you missing a cast?) tx.DNX 4.5.1 | Controllers\ManageController.cs 286

here is my project.json file
```json
{
  "webroot": "wwwroot",
  "userSecretsId": "xxx",
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-beta8",
    "EntityFramework.SqlServer": "7.0.0-beta8",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta8",
    "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta8",
    "Microsoft.AspNet.Authentication.Google": "1.0.0-beta8",
    "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta8",
    "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta8",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta8",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta8",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta8",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-beta8",
    "Microsoft.AspNet.Mvc": "6.0.0-beta8",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta8",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8",
    "Microsoft.AspNet.Session": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta8",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta8",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta8",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta8",
    "Microsoft.Framework.Configuration.UserSecrets": "1.0.0-beta8",
    "Microsoft.Framework.Logging": "1.0.0-beta8",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta8",
    "Microsoft.Framework.Logging.Debug": "1.0.0-beta8",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta8"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": {}
  },

}

```

**Comment by Tratcher** [comment]
Do not mix rc1 and beta8 packages.

**Comment by ahmad-moussawi** [comment]
@Tratcher Thanks :+1:

**Comment by muratg** [comment]
Closing this.  @ahmad-moussawi let us know if you still have issues when you move all your packages to RC1.
