### ISSUE TITLE
Registering caching together with session

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Session#75]
Adding session without adding caching always throws on first temp data access:
```C#
public void Configure(IApplicationBuilder app)
{
    app.UseSession();
    // Other code
}
public void ConfigureServices(IServiceCollection services)
{
    services.AddSession();
    // Other code
}
```
maybe `AddSession` could register caching by default if it's required anyways?
Because dependency injection says very little about what is wrong with me codez :octocat:

**Comment by Tratcher** [comment]
It doesn't add caching because it doesn't know what distributed cache you want to use. E.g. memory, redis, sql, etc.

**Comment by Muchiachio** [comment]
Couldn't it add memory by default with ability to override?

**Comment by Muchiachio** [comment]
Should I close this as won't fix?

**Comment by muratg** [comment]
@Muchiachio I don't know if using memory cache by default is a good idea. Closing as won't fix.
