### ISSUE TITLE
Consider AddSession over AddSessionServices

### ISSUE THREAD

**Issue by HaoK** [aspnet/Session#8]
Consistency with other AddXyz() methods, also nit:

https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNet.Session/CachingServicesExtensions.cs

Copy paste issue with class/file names

**Comment by Praburaj** [comment]
Merged : https://github.com/aspnet/Session/commit/6c57ca7c1ed61a34c14003d3382049243e9f9d95
