### ISSUE TITLE
The dependency Microsoft.AspNet.Session >= 1.0.0-rc1-final could not be resolved

### ISSUE THREAD

**Issue by wlopezob** [aspnet/Session#80]
My Project.json

"dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Session": "1.0.0-rc1-final",
    "Microsoft.AspNet.Http": "1.0.0-rc1-final",
    "Microsoft.AspNet.Http.Extensions": "1.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.DependencyInjection": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final"
  },

Install asp.net rc1 and when I download the asp.net session shows me the error: The dependency Microsoft.AspNet.Session> = 1.0.0-rc1-end Could not be resolved, not how to fix it.

thank you

**Comment by Tratcher** [comment]
?? There's nothing special about the Session package. Verify you're using the nuget.org feed. Have you tried this with any other added package?

**Comment by wlopezob** [comment]
I have no idea how to check if I'm using the nuget.org feed, just install the asp.net 5 rc1 which not download the "Microsoft.AspNet.Session": "1.0.0-rc1-final"

**Comment by Tratcher** [comment]
Does your project have a nuget.config file?

**Comment by wlopezob** [comment]
El proyecto es nuevo creado con visual studio 2015 community update 1, no encuentro el archivo NuGet.Config como se muestra en la imagen, es necesario reparar el visual studio?

![captura](https://cloud.githubusercontent.com/assets/16323429/11847646/7cddc82e-a3ec-11e5-996d-3e37f943567a.PNG)

**Comment by wlopezob** [comment]
Thanks for the support, I manually created the file with its contents:
<? xml version = "1.0" encoding = "utf-8"?>
<configuration>
   <packageSources>
     <add key = "api.nuget.org" value = "https://api.nuget.org/v3/index.json" />
   </ packageSources>
</ configuration>

when I run DNU reload tells me I should use the feed
  https://api.nuget.org/v3-flatcontainer/

should replace https://api.nuget.org/v3/index.json?

**Comment by muratg** [comment]
@wlopezob no that should be fine.  Can you try running `dnu restore` from the command line at the project directory (where `project.json` exists?)

**Comment by muratg** [comment]
Also, you should have a global nuget.config.  You can find it in VS (Tools/Options, search for nuget, select "Package Sources")  Does it only have nuget.org feed in the list?

**Comment by muratg** [comment]
@wlopezob Do you still have this issue?

**Comment by mikebrind** [comment]
I have this issue. Adding "Microsoft.AspNet.Session":"1.0.0-rc1-final" to *project.json* worked fine from another machine earlier today, but this evening the session package fails to resolve. When running `dnu restore` I get "Unable to locate Dependency Microsoft.AspNet.Session >= 1.0.0-rc1-final".

**Comment by Tratcher** [comment]
@mikebrind Sounds like a nuget.org issue or dnu/dnx issue. Nothing in this repo could cause that.

**Comment by muratg** [comment]
@mikebrind Are you sure your project.json contains the correct package name and version?  Because, In the error in your original report seems to have version: "1.0.0-rc1-**end**".  Can you try with a brand new app?

**Comment by mikebrind** [comment]
@muratg I didn't file the original report. My project.json and error messages both contain "Microsoft.AspNet.Session":"1.0.0-rc1-final". This is a brand new app. However, I tried with another brand new app and get the same error: NU1001	The dependency Microsoft.AspNet.Session >= 1.0.0-rc1-final could not be resolved.

**Comment by muratg** [comment]
@yishaigalatzer Any ideas why this could be?

**Comment by david-whitehead** [comment]
i also have the same issue as i posted on the forum https://forums.asp.net/p/2081559/6007318.aspx?Re+rc1+sessions, having had a further look into this problem even if i download nuget,exe console and try to do it external to VS i still get the same errors about not being able to find the package but i can transfer the exact same console nuget.exe onto any other machine and retrieve it without an issue.

**Comment by muratg** [comment]
This is really interesting.  Folks who are hitting this issue, could you try the following on the machines that have this problem?

Create a regular .NET app (not an ASP.NET 5, let's say a Console project) and add Session package from the NuGet UI (or PowerShell console).  If it is able to download and install it, this would potentially be a DNX/DNU issue.  If not, it's possibly a NuGet server issue with this particular package.

**Comment by wlopezob** [comment]
Good, solve the problem, manually creating the file  NuGet.Config in the folder  solution items, with the following contents:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

![solucion](https://cloud.githubusercontent.com/assets/16323429/12177034/3fefa722-b538-11e5-96d2-8d43d309556b.png)

**Comment by mikebrind** [comment]
That's a workaround, not an acceptable solution.

**Comment by muratg** [comment]
@mikebrind Could you try nuget.exe (or via VS on a a .NET 4.5 console project) to install this package, and see if it repros on your machine?  I tried several machines and couldn't repro this.

I want to understand if this is a nuget client, dnu, nuget server or machine configuration issue.

**Comment by mikebrind** [comment]
@muratg The install failed in a console app targeting 4.5 (You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework.) but it succeeded when I targeted 4.6.

**Comment by muratg** [comment]
@yishaigalatzer @emgarten This is an interesting issue, that repro's only on some machines with DNU. Creating a local a nuget.config seems to solve it.  Do you guys want to carry this over to nuget repo to track for the merger?

**Comment by muratg** [comment]
Need to move this to NuGet once we can get a repro.

**Comment by yishaigalatzer** [comment]
What in the world is https://api.nuget.org/v3-flatcontainer/ as a feed? That's not valid and we will not guarantee any support for it

**Comment by yishaigalatzer** [comment]
If this repros in the cli restore we can take a look otherwise the is no point in moving it

**Comment by hishamco** [comment]
Do we really need this open, while version 1.0.0 already released from awhile?
