### ISSUE TITLE
Caching in Sessions

### ISSUE THREAD

**Issue by NeelBhatt** [aspnet/Session#81]
I have wrote blog on sessions which is here: https://neelbhatt40.wordpress.com/2015/09/07/implement-sessions-in-asp-net-5vnext-and-mvc-6/

In this one person asked like Is it possible to use in-memory caching for general use at the same time as SQL server backed sessions?

I was not sure on this so i am asking it here!

**Comment by Tratcher** [comment]
Yes, they shouldn't interfere with each other. In memory caching is registered as an IMemoryCache, where SQL is registered as an IDistributedCache. Session uses IDistributedCache.

**Comment by NeelBhatt** [comment]
okay thanks for prompt reply :+1:

**Comment by NeelBhatt** [comment]
Hi @Tratcher..Is there any sample that show how to properly configure the services object with “In Memory Cache” and simultaneous “Sql Server Sessions”.?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Session/issues/84#issuecomment-168755803
