### ISSUE TITLE
Add an option when configuring service to always create cookie

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Session#83]
Normally when I'm making sites in other frameworks, I enjoy the fact that they will default to creating a session & cookie for every client.

It would appear as though in this library, the cookie is only set when some state is assigned to it.

Would be nice to have something like `alwaysCreate` or some better option name to `SessionOptions`.

**Comment by Tratcher** [comment]
By design. Any response that sets cookies also disables caching, so enabling alwaysCreate would disable caching on your home page. You also don't want to create it for API requests, etc..

**Comment by atrauzzi** [comment]
Ah, yes, very true.  Could it be in the call in configure instead then?  That way some logic can be leveraged before forcing it on.

**Comment by Tratcher** [comment]
You could just do that in app code:
```
app.Use((context, next) =>
{
  if (ShouldEnableSession(context))
  {
    context.Session.Set("Enabled", true);
  }
  return next();
});
```

**Comment by atrauzzi** [comment]
Works for me!  Thanks for the clarification on the API's flexibility. :)

**Comment by atrauzzi** [comment]
Actually, now that I think about it, isn't that just setting an arbitrary value?

**Comment by Tratcher** [comment]
What's the point if there's no data associated with it?

**Comment by atrauzzi** [comment]
The client will ship it back on subsequent requests and will give me something to track against at the HTTP layer.

**Comment by Tratcher** [comment]
Ah, you want a correlation id. You can do that with your own cookie. There's no reason to force a session cookie for that.

**Comment by atrauzzi** [comment]
Sure, but why heap up several cookies?  Why not just use the one and tie all server-tracked state to it?  If I make my own, then I'll have session and security on top of it eventually.

**Comment by Tratcher** [comment]
Because you'll be in control of its lifetime and configuration without artificially modifying the mechanics of other components.

**Comment by atrauzzi** [comment]
Hmm, alright.  I think I'm going to try and work with that philosophy in mind.

Apologies, I'm coming from a PHP world where a framework built on top of the language will manage a single session and usually expose it throughout with an API.  This usually meant we only ever worked with one session that everyone campfired around ;)
