### ISSUE TITLE
SQL Session with simultaneous In-Memory Cache?

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/Session#84]
Is it possible to run SQL backed Session while simultaneously using in-memory implementation for general caching?  

*If so, can you point me to some samples of how to properly configure the services to accomplish that scenario?*

My use case is needing out-of-proc sessions (due to load balancing bouncing users around servers) while at the same time wanting the performance of in-proc caching for controller output fragments, etc.

Thanks!

**Comment by davidfowl** [comment]
Session is *always* backed by an `IDistributedCache` implementation. `IMemoryCache` is a different interface completely. Are you asking if you can use 2 implementations of session within the same app or are you asking if you can configure session to use the SQL implementation of `IDistributedCache` and also use `IMemoryCache` for other things? 

If it's the latter, then yes, because those are 2 different interfaces that becomes trivial.

**Comment by Tratcher** [comment]
Sounds like he wants IDistributedCache for session and IMemoryCache for other stuff. Yes, that's just fine. Go look at the cache repo samples.

**Comment by SimonOrdo** [comment]
Right, so the sample at https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs says to do something like this:

    // Uncomment the following line to use the Microsoft SQL Server implementation of IDistributedCache.
            // Note that this would require setting up the session state database.
            //services.AddSqlServerCache(o =>
            //{
            //    o.ConnectionString = "Server=.;Database=ASPNET5SessionState;Trusted_Connection=True;";
            //    o.SchemaName = "dbo";
            //    o.TableName = "Sessions";
            //});

I'm probably completely misinterpreting this, but to me that implies that in order to have SQL backed sessions, I need to change caching to also use a SQL store. 

I I have all three:
````
services.AddSqlServerCache(); // add SQL backed implementation of IDistributedCache ?
services.AddCaching(); // add IMemoryCache,IDistributedCache for general in-proc caching?
services.AddSession(); 
````

The sample implies that without line 1 AddSqlServerCache(), the call to AddSession() results in the use of the IMemoryCache added from the call to AddCaching()?  

How does AddSession know to use the SQL IDistributedCache instead of the IMemoryCache?

Am I just completely confused about how any of this works?  LOL!

**Comment by Tratcher** [comment]
Session always uses IDistributedCache
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNet.Session/SessionServiceCollectionExtensions.cs#L27
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNet.Session/DistributedSessionStore.cs#L16
AddCaching adds a IDistributedCache implemented using IMemoryCache:
https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Memory/MemoryCacheServicesExtensions.cs#L23
If you replace that IDistributedCache registration with AddSqlServerCache then you use SQL distributed cache, but IMemoryCache is still registered as a seperate service.

**Comment by SimonOrdo** [comment]
Oh, I see.  So the order in which I register them is key to making this work?  Specifically, for my scenario it needs to be:

AddCaching(); // Add IMemoryCache and IDistributedCache
AddSqlServerCache(); // overwrite IDistributedCache registration from AddCaching with SQL backing
AddSession(); // which will now resolve to using SQL backed IDistributedCache

Is that about right?

**Comment by Tratcher** [comment]
Yes, that should work.

**Comment by SimonOrdo** [comment]
Phew!  Thank for your time!  I appreciate the help.
