### ISSUE TITLE
Memory-backed session doesn't seem to be working correctly in RC1

### ISSUE THREAD

**Issue by mikebrind** [aspnet/Session#85]
I'm having difficulty getting session variables to persist across requests when using `Microsoft.Extensions.Caching.Memory`. Steps to reproduce are:

1. Create a new project using the ASP.NET 5 Web Application template in VS 2015 Update1, with no authentication.
2. Add the following to the end of the _project.json_ file:
```
"Microsoft.AspNet.Http": "1.0.0-rc1-final",
"Microsoft.AspNet.Session": "1.0.0-rc1-final",
"Microsoft.Extensions.Caching.Memory": "1.0.0-rc1-final"
```
3. Amend the StartUp.ConfigureServices method as follows:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddCaching().AddSession().AddMvc();
}
```
4. Add `app.UseSession();` to the beginning of the `Configure` method.
5. Add `using Microsoft.AspNet.Http;` to the HomeController class and amend the Index and About methods:
```
public IActionResult Index()
{
    HttpContext.Session.SetString("Message", "Hello World");
    return View();
}

public IActionResult About()
{
    ViewData["Message"] = HttpContext.Session.GetString("Message");
    return View();
}
```

When I add a breakpoint to the Index method, I can see that the Session `_store` has a Count = 1, but the backing store (`_memCache`) has 0 entries. When the About method is invoked afterwards, the session collection has 0 entries.

Am I overlooking something?

**Comment by Tratcher** [comment]
The session isn't written to the memory cache until the end of the first request. It should be available on the next request unless A) the client didn't send back the session cookie, or B) the memory cache entry expired and/or was removed.

Try enabling logging (https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs#L17) to see if it gives you more details.

**Comment by mikebrind** [comment]
Or C) you have multiple existing cookies named .AspNet.Session, which was my issue.  I'll check my work machine on Monday to see if that was the issue there too, and will also note when the cookies were written, if I find any.

**Comment by mikebrind** [comment]
Clearing all cookies for the domain resolved the issue.
