### ISSUE TITLE
Getting new session id for every web request

### ISSUE THREAD

**Issue by RickOregon** [aspnet/Session#91]
Session is not maintained between web requests.

In Startup->ConfigureServices() 
   services.AddMvc();
   services.AddCaching();
   services.AddSession();

In Startup->Configure()
   app.UseSession();
   app.UseMVC(...)

I see the services.AddSession() has:
ServiceCollectionExtensions.AddTransient<ISessionStore, DistributedSessionStore>(services);

Should this be a scoped service?

**Comment by hishamco** [comment]
The ```AddTransient``` extension is create an instance each time you ask the DI, ```AddScoped``` extension is the one you are looking which is create an instance for each request

**Comment by Tratcher** [comment]
It shouldn't matter, the cache is only resolved once in the middleware constructor at startup. I suspect this is not the cause of your issue.

**Comment by RickOregon** [comment]
Not sure what changed, but the issue seems to have resolved itself.   This was just the vanilla new Web app generated by visual studio with the few additions to enable session.  Previously every post got a new session (examining in the debugger showed a new session id).    No idea what changed to alter the behavior.

**Comment by muratg** [comment]
Looks like this is resolved. @RickOregon please file another one if you see a regression, and thanks for your report!
