### ISSUE TITLE
Getting session id

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Session#93]
As seen at https://github.com/aspnet/Session/issues/49 reading session ids aren't supported anymore? 

Are there any plans to still get the session-id? Because this is a big breaking change - and in my opinion unneeded. 

We need it for logging purposes. Maybe session-ids aren't perfect, but AFAIK there are still existing (but not readable).

**Comment by Tratcher** [comment]
No, everything we said in #49 is still accurate.

**Comment by 304NotModified** [comment]
Not to be picky, but `It's not intended for application usage,` says nothing about future plans or breaking changes. 

IMO we should not be light on breaking changes. It should be well documented also.
