### ISSUE TITLE
Add sessionid to isession 

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Session#96]
The sessionid is already used  in some parts like logging and creating sessions. With that in mind, it's strange that we can't  read the sessionid when we use isession - it seems that sessionid is a important part of the whole session (otherwise why log it) . 

Also in the previous versions of asp.Net,  the sessionid was readable.  

So please think of including sessionid in isession.  

(limited Internet device now - mobile - so ignore the full lowercase names)

**Comment by Tratcher** [comment]
https://github.com/aspnet/Session/issues/49

**Comment by 304NotModified** [comment]
really, why is it logged then?

**Comment by 304NotModified** [comment]
open source seems a joke here as issues are closed without even a proper response.

**Comment by Tratcher** [comment]
It's logged only for diagnostic purposes.

**Comment by 304NotModified** [comment]
> It's logged only for diagnostic purposes.

Precisely. So if an user would log more related info for diagnostic purposes, like the current request. Why should we not use the sessionId then? How do we relate diagnostic info without the sessionid? Why should we use our own id (change in software), while the sessionId is far more appropriate?  Why do we need to change our software, while we would like to capture our current program and not a changed one?

**Comment by Tratcher** [comment]
The cookie value is only loosely associated with the actual session. The actual session is the cache entry stored in the distributed cache. This can vanish for a number of reasons that would not affect the cookie, and then you would get a new session on the next request that still has the same cookie value. That's why we recommend storing your own identifier value in the session.

**Comment by Tratcher** [comment]
Maybe there's a better way to go about this. We've covered why the cookie value would not make a good ISession.Id, but that doesn't mean there can't be some Id. There's no reason we can't include some guid as part of the content stored with the session itself, independent of the cookie.

**Comment by 304NotModified** [comment]
Thanks! That sounds like a good idea :) 

> The cookie value is only loosely associated with the actual session. The actual session is the cache entry stored in the distributed cache. This can vanish for a number of reasons that would not affect the cookie, and then you would get a new session on the next request that still has the same cookie value. That's why we recommend storing your own identifier value in the session.

Independent of the sessionGuid, can something like this added to DistributedSession? I'm also not sure if this behavior is different compared to ASP.NET 4.
